import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkLoaded, ClerkProvider, UserProfile } from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <ClerkLoaded>
            <div
              className="h-screen"
              style={{
                width: 60,
                height: 60,
                marginLeft: "auto",
                marginTop: 20,
              }}
            >
              {" "}
              <UserButton afterSignOutUrl="/" />
              {/* <UserProfile appearance={{}} /> */}
            </div>
            {children}
          </ClerkLoaded>
        </ClerkProvider>
      </body>
    </html>
  );
}
