import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div
            className="h-screen"
            style={{ width: 60, height: 60, marginLeft: "auto", marginTop: 20 }}
          >
            {" "}
            <UserButton afterSignOutUrl="/" />
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
